---
timeout: 300
dontChroot: true
script:
    - bash -c "mount --bind /dev /tmp/calamares-root/dev && mount --bind /proc /tmp/calamares-root/proc && mount --bind /sys /tmp/calamares-root/sys && chroot /tmp/calamares-root /usr/lib/velox-installer/install.sh"
    - find /tmp/calamares-root/home -name "*.desktop" -exec grep -l -i calamares {} \; | xargs rm -f 2>/dev/null || true
    - find /tmp/calamares-root/root -name "*.desktop" -exec grep -l -i calamares {} \; | xargs rm -f 2>/dev/null || true
