---
dontChroot: true
script:
    - mkdir -p /tmp/calamares-root/boot
    - cp /tmp/velox-boot/vmlinuz-linux /tmp/calamares-root/boot/vmlinuz-linux
    - cp /tmp/velox-boot/initramfs-linux.img /tmp/calamares-root/boot/initramfs-linux.img
    - bash /etc/calamares/scripts/install-grub.sh
    - find /tmp/calamares-root/home -name "*.desktop" -exec grep -l -i calamares {} \; | xargs rm -f
    - find /tmp/calamares-root/root -name "*.desktop" -exec grep -l -i calamares {} \; | xargs rm -f
