---
dontChroot: true
script:
    - mkdir -p /tmp/velox-boot
    - cp /run/archiso/bootmnt/arch/boot/x86_64/vmlinuz-linux /tmp/velox-boot/vmlinuz-linux
    - cp /run/archiso/bootmnt/arch/boot/x86_64/initramfs-linux.img /tmp/velox-boot/initramfs-linux.img
