---
script:
    - bash /usr/lib/velox-installer/install.sh
    - find /home -name "*.desktop" -exec grep -l -i calamares {} \; | xargs rm -f 2>/dev/null || true
    - find /root -name "*.desktop" -exec grep -l -i calamares {} \; | xargs rm -f 2>/dev/null || true
