---
# Velox Linux users configuration

defaultGroups:
  - name: users
    must_exist: false
    system: false
  - name: lp
    must_exist: false
    system: false
  - name: video
    must_exist: false
    system: false
  - name: network
    must_exist: false
    system: false
  - name: storage
    must_exist: false
    system: false
  - name: wheel
    must_exist: false
    system: false
  - name: audio
    must_exist: false
    system: false
  - name: optical
    must_exist: false
    system: false

autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    wheel
setRootPassword: true
doReusePassword: true

passwordRequirements:
  minLength: 0

avatarFilePath: ~/.face
