---
# Velox Linux welcome module configuration

showSupportUrl:        true
showKnownIssuesUrl:    true
showReleaseNotesUrl:   false
showDonateUrl:         false

requirements:
  requiredStorage:     20
  requiredRam:         2.0
  internetCheckUrl:    "https://github.com"
  check:
    - storage
    - ram
    - power
    - internet
  required:
    - storage
    - ram
