[Icon Theme]
Name=Newaita-Velox
Comment=Newaita with Velox green folders
Inherits=Newaita
Directories=places/16,places/22,places/24,places/32,places/48,places/64,places/16@2x,places/22@2x,places/24@2x,places/32@2x,places/48@2x,places/64@2x,places/symbolic,apps/16,apps/22,apps/24,apps/32,apps/48,apps/64

[places/16]
Size=16
Type=Scalable

[places/22]
Size=22
Type=Scalable

[places/24]
Size=24
Type=Scalable

[places/32]
Size=32
Type=Scalable

[places/48]
Size=48
Type=Scalable

[places/64]
Size=64
Type=Scalable

[places/16@2x]
Size=16
Scale=2
Type=Scalable

[places/22@2x]
Size=22
Scale=2
Type=Scalable

[places/24@2x]
Size=24
Scale=2
Type=Scalable

[places/32@2x]
Size=32
Scale=2
Type=Scalable

[places/48@2x]
Size=48
Scale=2
Type=Scalable

[places/64@2x]
Size=64
Scale=2
Type=Scalable

[apps/16]
Size=16
Type=Fixed

[apps/22]
Size=22
Type=Fixed

[apps/24]
Size=24
Type=Fixed

[apps/32]
Size=32
Type=Fixed

[apps/48]
Size=48
Type=Fixed

[apps/64]
Size=64
Type=Fixed

[places/symbolic]
Size=48
MinSize=16
MaxSize=512
Type=Scalable
Context=Places
