[Application Menu]
icon=start-here-kde
label=Applications

[Clock]
fontScaleFactor=1
use24HourClock=true

[General]
backgroundColor=15,11,13,190
borderColor=122,134,139
maximumIconSize=52
minimumIconSize=28
showBorder=false
spacingFactor=0.5
tooltipFontSize=20

