[Autologin]
Relogin=false
Session=plasma        # ← change from xfce
User=liveuser

[General]
HaltCommand=/usr/bin/systemctl poweroff
Numlock=on
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=breeze-velox        # ← change from arcolinux-simplicity
CursorTheme=breeze_cursors   # ← swap Bibata for Breeze (comes with Plasma)
Font=Noto Sans,10,-1,0,50,0,0,0,0,0

[Users]
MaximumUid=60513
MinimumUid=1000
