[General]
background=/usr/share/wallpapers/Velox-8/contents/images/3840x2160.png
blur=true
recursiveBlurLoops=4
recursiveBlurRadius=4
blurRadius=100
passwordCharacter=●
sessionButtonPosition=left
showUserRealNameByDefault=true
