#!/usr/bin/env bash
# shellcheck disable=SC2034

iso_name="velox"
iso_label="VELOX_$(date +%Y%m)"
iso_publisher="Velox Linux <https://github.com/thelinuxtubetltos/velox-iso>"
iso_application="Velox Linux Live/Rescue DVD"
iso_version="v8.3.0"
install_dir="arch"
buildmodes=('iso')
bootmodes=('bios.syslinux'
           'uefi.systemd-boot')
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
#airootfs_image_tool_options=('-comp' 'xz' '-Xbcj' 'x86')
#airootfs_image_tool_options=('-comp' 'xz' '-Xbcj' 'x86' '-b' '1M' '-Xdict-size' '1M')
#airootfs_image_tool_options=('-comp' 'zstd' '-Xcompression-level' '6')
airootfs_image_tool_options=('-comp' 'zstd' '-Xcompression-level' '1' '-b' '1M')
bootstrap_tarball_compression=(zstd -19)
file_permissions=(
  ["/etc/gshadow"]="0:0:400"
  ["/etc/shadow"]="0:0:400"
  ["/root"]="0:0:750"
  ["/root/.automated_script.sh"]="0:0:755"
  ["/root/.gnupg"]="0:0:700"
  ["/etc/polkit-1/rules.d"]="0:0:750"
  ["/etc/sudoers.d"]="0:0:750"
  ["/etc/grub.d/40_custom"]="0:0:755"
  ["/usr/bin/velox-welcome"]="0:0:755"
  ["/usr/lib/velox-installer/run-install.sh"]="0:0:755"
  ["/usr/lib/velox-installer/install.sh"]="0:0:755"
  ["/usr/lib/velox-installer/apply-desktop-skel.sh"]="0:0:755"
  ["/usr/lib/velox-installer/install-velox-desktop.sh"]="0:0:755"
  ["/usr/lib/velox-installer/velox-cinnamon-firstboot.sh"]="0:0:755"
  ["/usr/lib/velox-installer/setup-btrfs.sh"]="0:0:755"
  ["/usr/lib/velox-installer/cleanup-backgrounds.sh"]="0:0:755"
  ["/usr/bin/calamares-launcher"]="0:0:755"
  ["/usr/bin/velox-live-start"]="0:0:755"
  ["/usr/bin/velox-set-resolution"]="0:0:755"
  ["/usr/bin/velox-launcher"]="0:0:755"
  ["/usr/bin/velox-reload-desktop"]="0:0:755"
  ["/usr/local/bin/velox-sddm-kwin-start"]="0:0:755"
  ["/usr/local/bin/velox-sddm-sync-output"]="0:0:755"
  ["/usr/local/bin/ksmoothdock-start"]="0:0:755"
  ["/usr/bin/velox-update-notifier"]="0:0:755"
  ["/usr/local/bin/ksmoothdock-patch"]="0:0:755"
  ["/usr/local/bin/velox-xfce-start"]="0:0:755"
  ["/usr/lib/velox-desktops/kde/apply-papirus-green-folders.sh"]="0:0:755"
  ["/usr/share/sddm/scripts/Xsetup"]="0:0:755"
  ["/var/lib/sddm/.config/kwinoutputconfig.json"]="0:0:644"
  ["/home/liveuser/.config/openbox/autostart"]="1000:1000:755"
  ["/home/liveuser/.config/openbox/rc.xml"]="1000:1000:644"
  ["/home/liveuser/Desktop/install-velox.desktop"]="1000:1000:755"
  ["/home/liveuser/.config/autostart/calamares.desktop"]="1000:1000:755"
)
