[General]
showlogo=hidden
showClock=true
logo=/usr/share/sddm/themes/breeze/default-logo.svg
type=image
color=#3a5228
fontSize=10
background=/usr/share/wallpapers/Velox-8/contents/images/3840x2160.png
needsFullUserModel=false
