title    Velox Linux (%ARCH%, UEFI)
sort-key 01
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-velox
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-velox.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% driver=free cow_spacesize=4G copytoram=n module_blacklist=nvidia,nvidia_modeset,nvidia_uvm,nvidia_drm,pcspkr nouveau.modeset=1 radeon.modeset=1 i915.modeset=1 nvme_load=yes quiet loglevel=3 video=1920x1080
