title    Velox Linux (%ARCH%, UEFI, safe graphics)
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-velox
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-velox.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% driver=free cow_spacesize=4G copytoram=n nomodeset module_blacklist=nvidia,nvidia_modeset,nvidia_uvm,nvidia_drm,pcspkr nouveau.modeset=0 radeon.modeset=0 i915.modeset=0 nvme_load=yes quiet loglevel=3
